version: "3.9"
services:
  eventstore:
    image: "eventstore/eventstore:latest"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - type: volume
        source: eventstore-communications-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-communications-logs
        target: /var/log/eventstore

volumes:
  eventstore-communications-data:
  eventstore-communications-logs:
